import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function BuildGuide() {
  return (
    <div>
      <Head>
        <title>Inexpensive Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ie.ico" />
      </Head>

      <div className={styles.bar}>
        <div className={styles.homeLink}>
          <Link href="/">
            <a>
              <h2>Inexpensive Gaming</h2>
            </a>
          </Link>
        </div>

        <div className={styles.links}>
          <Link href="/parts">
            <a>
              <h3>Parts</h3>
            </a>
          </Link>

          <Link href="/buildguide">
            <a>
              <h3>Build Guide</h3>
            </a>
          </Link>

          <Link href="/benchmarks">
            <a>
              <h3>Benchmarks</h3>
            </a>
          </Link>
        </div>
      </div>

      <ul>
        <h3>Step one</h3>
      </ul>
      <ul>Make sure all parts are undamaged.</ul>
      <ul>
        <h3>Step two</h3>
      </ul>
      <ul>Lift the latch on the motherboard where the CPU goes</ul>
      <ul>
        <h3>Step three</h3>
      </ul>
      <ul>Insert CPU by lining up the triangles on both the socket and the CPU and then close and lock the latch.</ul>
      <ul>
        <h3>Step four</h3>
      </ul>
      <ul>Push the tabs on both sides of each memory slot open on which you will be using. If using two sticks, refer to the motherboard manual on which slots to use.</ul>
      <ul>
        <h3>Step five</h3>
      </ul>
      <ul>Gently place each stick of memory into its corresponding slot and press until both sides latch in.</ul>
      <ul>
        <h3>Step six</h3>
      </ul>
      <ul>With the side of the case where the motherboard goes open, gently place the motherboard in its resting spot making sure to line the holes up with the threads where the screws will go as well as the rear I/O panel.</ul>
      <ul>
        <h3>Step seven</h3>
      </ul>
      <ul>Screw in the motherboard using the supplied screws from the case.</ul>
      <ul>
        <h3>Step eight</h3>
      </ul>
      <ul>Remove the PCI brackets from the case where the graphics card will go.</ul>
      <ul>
        <h3>Step nine</h3>
      </ul>
      <ul>With the latch on the motherboard where the graphics card goes open, gently slot the graphics card in until it clicks and then screw it into the case using the cases hardware.</ul>
      <ul>
        <h3>Step ten</h3>
      </ul>
      <ul>Slide the power supply into the case and screw it in using the cases supplied hardware.</ul>
      <ul>
        <h3>Step eleven</h3>
      </ul>
      <ul>While referencing the motherboard manual, put each needed cable into both the motherboard and the power supply. Also, put the cables in for the graphics card.</ul>
      <ul>
        <h3>Step twelve</h3>
      </ul>
      <ul>Again using the motherboard manual as a reference and also the case manual, connect all cables from the case to the motherboard.</ul>
      <ul>
        <h3>Step thirteen</h3>
      </ul>
      <ul>Insert your storage into the case and use the supplied motherboard and powersupply cables to connect them. The motherboard manual also helps with this.</ul>
      <ul>
        <h3>Step fourteen</h3>
      </ul>
      <ul>Check that all cables are in the right place and then flip the switch on the power supply to the on position.</ul>
      <ul>
        <h3>You have now built a pc!</h3>
      </ul>
      <ul>
        <h3>For more in depth tutorials, we recommend these videos:</h3>
      </ul>
      <ul>
        <Link href="https://www.youtube.com/watch?v=v7MYOpFONCU&ab_channel=LinusTechTips">
          <a>
            <h3>Linus</h3>
          </a>
        </Link>
      </ul>
      <ul>
        <Link href="https://www.youtube.com/watch?v=DwyNpQ_T578&ab_channel=AustinEvans">
          <a>
            <h3>Austin Evans</h3>
          </a>
        </Link>
      </ul>
    </div>
  )
}