import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Inexpensive Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ie.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Inexpensive Gaming
        </h1>

        <div className={styles.bar}>
          <Link href="/parts">
            <a className={styles.barItem}>
              <h2>Parts</h2>
            </a>
          </Link>

          <Link href="/buildguide">
            <a className={styles.barItem}>
              <h2>Build Guide</h2>
            </a>
          </Link>

          <Link href="/benchmarks">
            <a className={styles.barItem}>
              <h2>Benchmarks</h2>
            </a>
          </Link>
        </div>

        <div className={styles.container}>
          <h1>Best Deals</h1>
          <h2>Coming Soon</h2>
        </div>
      </main>
    </div>
  )
}
