import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Inexpensive Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ie.ico" />
      </Head>

      <div className={styles.bar}>
        <Link href="/">
          <a>
            <h2>Inexpensive Gaming</h2>
          </a>
        </Link>

        <div className={styles.links}>
          <Link href="/parts">
            <a>
              <h3>Parts</h3>
            </a>
          </Link>

          <Link href="/buildguide">
            <a>
              <h3>Build Guide</h3>
            </a>
          </Link>

          <Link href="/benchmarks">
            <a>
              <h3>Benchmarks</h3>
            </a>
          </Link>
        </div>
      </div>

      <main className={styles.main}>
        <div className={styles.container}>
          <h1>Best Deals</h1>
          <h2>Coming Soon</h2>
        </div>
      </main>
    </div>
  )
}
