import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Head from 'next/head'

export default function parts() {
  return (
    <div>
      <Head>
        <title>Inexpensive Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ie.ico" />
      </Head>

      <div className={styles.bar}>
        <Link href="/">
          <a>
            <h2>Inexpensive Gaming</h2>
          </a>
        </Link>

        <div className={styles.links}>
          <Link href="/parts">
            <a>
              <h3>Parts</h3>
            </a>
          </Link>

          <Link href="/buildguide">
            <a>
              <h3>Build Guide</h3>
            </a>
          </Link>

          <Link href="/benchmarks">
            <a>
              <h3>Benchmarks</h3>
            </a>
          </Link>
        </div>
      </div>

      <main className={styles.main}>
        <div>
          <h2 className={styles.title}>What parts are you looking for?</h2>
        </div>

        <div className={styles.grid}>
          <Link href="/parts/graphics-cards">
            <a className={styles.card}>
              <h2>Graphics Cards &rarr;</h2>
            </a>
          </Link>

          <Link href="/parts/cpus">
            <a className={styles.card}>
              <h2>CPUs &rarr;</h2>
            </a>
          </Link>

          <Link href="/parts/motherboards">
            <a className={styles.card}>
              <h2>Motherboards &rarr;</h2>
            </a>
          </Link>

          <Link href="/parts/memory">
            <a className={styles.card}>
              <h2>Memory &rarr;</h2>
            </a>
          </Link>

          <Link href="/parts/power-supplies">
            <a className={styles.card}>
              <h2>Power Supplies &rarr;</h2>
            </a>
          </Link>

          <Link href="/parts/cases">
            <a className={styles.card}>
              <h2>Cases &rarr;</h2>
            </a>
          </Link>

          <Link href="/parts/cooling">
            <a className={styles.card}>
              <h2>Cooling &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}